redis:
  hostname: localhost
  port: 6379
---
spring:
  profiles: development

server.port: 8081

redis:
  hostname: localhost
  port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "health,jolokia,metrics"
  metrics:
    export:
      influx:
        db: ceres
        uri: http://localhost:8086
        auto-create-db: true
---
spring:
  profiles: production

redis:
  hostname: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}
management:
  endpoints:
    web:
      exposure:
        include: "health,jolokia,metrics"
  metrics:
    export:
      influx:
        db: ceres
        uri: ${INFLUXDB_METRICS_URL}
        auto-create-db: true