redis:
  hostname: localhost
  port: 6379
---
spring:
  profiles: development

redis:
  hostname: localhost
  port: 6379
---
spring:
  profiles: production

redis:
  hostname: ${REDIS_HOSTNAME}
  port: ${REDIS_PORT}